### ISSUE TITLE
可以加入你的项目吗？

### ISSUE THREAD

**Issue by abnerSK** [txbzjr/Nav_hi#3]
Hi!非常感谢你的精美的小工具，虽然现在ROOT用户越来越少，但这款工具还是解决了ROOT用户很大的难题，之前没有类似的应用。
我是一名学生，目前在欧洲读计算机硕士，请问可以为项目添加英文README以及未来一些修改吗

**Comment by txbzjr** [comment]
可以，欢迎加入

**Comment by txbzjr** [comment]
我们可以添加一下社交软件吗，我只有微信：13250111185

**Comment by txbzjr** [comment]
已发送合作邀请！O(∩_∩)O~~

**Comment by txbzjr** [comment]
这是我自学安卓中的第一个实际系统工具噢。

**Comment by txbzjr** [comment]
现在有一个bug和一个功能：bug是不能多个应用同时隐藏；功能是添加保存设置之类

**Comment by txbzjr** [comment]
忘了介绍自己，我是一名大专生，正步入工作，目前实习生
